spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka_example
    username: kafka
    password: root
    jpa:
      hibernate:
        dll-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  flyway:
    baseline-on-migrate: true